In [1]:
import pandas as pd

In [2]:
games = pd.read_csv('vgchartz-2024.csv')

In [4]:
games

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [5]:
games.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [6]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [10]:
games['release_date'] = pd.to_datetime(games['release_date'], errors='coerce', dayfirst=False)

In [11]:
games['relese_year'] = games['release_date'].dt.year
games['relese_month'] = games['release_date'].dt.month

In [12]:
games['release_date'].dtype

dtype('<M8[ns]')

In [13]:
games.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,relese_year,relese_month
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN,2013.0,9.0
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03,2014.0,11.0
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN,2002.0,10.0
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN,2013.0,9.0
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14,2015.0,11.0

In [15]:
games['relese_year'] = games['relese_year'].astype('Int64')
games['relese_month'] = games['relese_month'].astype('Int64')
games.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,relese_year,relese_month
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN,2013,9
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03,2014,11
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN,2002,10
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN,2013,9
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14,2015,11

In [23]:
title_group = games.groupby(['title','relese_year','relese_month']).agg({'critic_score':'mean', 'total_sales':'sum', 'na_sales':'sum', 'jp_sales':'sum', 'pal_sales':'sum', 'other_sales':'sum'}).sort_values(['total_sales'], ascending = False)
title_group

,,,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
title,relese_year,relese_month,,,,,,
Grand Theft Auto V,2013,9,9.400000,36.18,15.43,1.05,15.18,4.54
Call of Duty: Black Ops,2010,11,8.133333,30.99,17.65,0.59,9.45,3.31
Call of Duty: Modern Warfare 3,2011,11,7.500000,30.71,15.57,0.62,11.26,3.26
Call of Duty: Black Ops II,2012,11,8.375000,29.59,14.12,0.72,11.08,3.67
Call of Duty: Ghosts,2013,11,7.833333,28.80,15.06,0.49,9.60,3.65
...,...,...,...,...,...,...,...,...
percussONE,2009,2,NaN,0.00,0.00,0.00,0.00,0.00
peakvox: Escape Virus - Shooter Pack,2011,8,NaN,0.00,0.00,0.00,0.00,0.00
painball,2008,11,NaN,0.00,0.00,0.00,0.00,0.00
pOp+ Solo,2009,8,NaN,0.00,0.00,0.00,0.00,0.00
- Arcane RERaise -,2017,4,NaN,0.00,0.00,0.00,0.00,0.00

In [19]:
year_month_group = games.groupby(['relese_year','relese_month']).agg({'critic_score':'mean', 'total_sales':'sum', 'na_sales':'sum', 'jp_sales':'sum', 'pal_sales':'sum', 'other_sales':'sum'}).sort_values(['total_sales'], ascending = False)
year_month_group

                          critic_score  total_sales  na_sales  jp_sales  \
relese_year relese_month
2011        11                7.758824       135.99     67.28      5.66
2008        10                7.382927       126.12     73.23      2.24
2007        11                7.159420       123.16     67.97      3.34
2009        10                7.293443       115.54     60.67      4.37
2007        10                7.070732       114.03     63.35      2.93
...                                ...          ...       ...       ...
2021        3                      NaN         0.00      0.00      0.00
            4                 8.500000         0.00      0.00      0.00
            5                      NaN         0.00      0.00      0.00
            6                      NaN         0.00      0.00      0.00
2022        11                     NaN         0.00      0.00      0.00

                          pal_sales  other_sales
relese_year relese_month
2011        11                47.84        15.29
2008        10                34.41        16.22
2007        11                35.14        16.78
2009        10                34.58        15.93
2007        10                28.43        18.98
...                             ...          ...
2021        3                  0.00         0.00
            4                  0.00         0.00
            5                  0.00         0.00
            6                  0.00         0.00
2022        11                 0.00         0.00

[528 rows x 6 columns]

In [21]:
Pivot_Console_By_Genre = games.pivot_table(index='console',columns='genre', values='title', aggfunc = 'count')
Pivot_Console_By_Genre

genre,Action,Action-Adventure,Adventure,Board Game,Education,Fighting,MMO,Misc,Music,Party,Platform,Puzzle,Racing,Role-Playing,Sandbox,Shooter,Simulation,Sports,Strategy,Visual Novel
console,,,,,,,,,,,,,,,,,,,,
2600,302.0,NaN,3.0,NaN,NaN,3.0,NaN,21.0,NaN,NaN,17.0,19.0,19.0,4.0,NaN,68.0,4.0,39.0,2.0,NaN
3DO,12.0,NaN,43.0,NaN,NaN,13.0,NaN,88.0,NaN,NaN,7.0,13.0,10.0,10.0,NaN,37.0,23.0,35.0,14.0,NaN
3DS,198.0,34.0,63.0,NaN,1.0,18.0,1.0,382.0,11.0,8.0,76.0,78.0,22.0,125.0,NaN,20.0,75.0,49.0,26.0,5.0
5200,26.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,6.0,2.0,NaN,NaN,20.0,1.0,7.0,NaN,NaN
7800,21.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,6.0,3.0,3.0,NaN,NaN,9.0,2.0,12.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XOne,309.0,211.0,216.0,2.0,1.0,91.0,10.0,67.0,27.0,10.0,120.0,67.0,129.0,197.0,3.0,201.0,81.0,137.0,71.0,13.0
XS,63.0,121.0,94.0,1.0,NaN,18.0,4.0,5.0,5.0,5.0,35.0,17.0,36.0,75.0,NaN,65.0,37.0,16.0,20.0,3.0
ZXS,5.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iOS,20.0,14.0,16.0,NaN,NaN,NaN,NaN,21.0,1.0,NaN,9.0,13.0,4.0,24.0,NaN,7.0,11.0,3.0,11.0,1.0
iQue,2.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,2.0,4.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN

In [26]:
with pd.ExcelWriter('GAMES_from_Python.xlsx', engine='openpyxl') as writer:
    title_group.to_excel(writer, sheet_name='titles_per_year_months')
    Pivot_Console_By_Genre.to_excel(writer, sheet_name='ConsolesByGenres')